# "release" runner tag is to make target hosts deterministic for easy clean up.
# TODO: Remove the "release" runner tag when installer tests are stable.
name: Release Homebrew
on:
  workflow_dispatch:

jobs:
  get-latest-tag:
    name: Get the latest release tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.latesttag.outputs.tag }}
      version: ${{ steps.latestversion.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: 'Get the latest tag'
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: 'Convert tag to version'
        id: latestversion
        run: |
          version=${{ steps.latesttag.outputs.tag }}
          if [ -z $version ]; then
            echo ERROR: Failed to get the latest tag
            exit 1
          fi
          if [[  $version == v* ]]; then
            version="${version:1}"
          fi
          echo "version=$version" >> ${GITHUB_OUTPUT}

  macos-amd64-test-installer:
    needs: get-latest-tag
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            [self-hosted, macos, amd64, 13.0, release],
          ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      FINCH_TAG: v0.3.0
      FINCH_VERSION: 0.3.0
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.FINCH_TAG }}
      - name: Clean up previous files
        run: |
          cd $(brew --repo homebrew/cask) 
          brew uninstall --cask ./Casks/finch.rb || true
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Bump local cask version
        run: |
          brew update-reset 
          export HOMEBREW_NO_INSTALL_FROM_API=1
          cd $(brew --repo homebrew/cask)
          echo "Update the local Finch cask with version $FINCH_VERSION"
          brew bump-cask-pr --write-only -f --version=$FINCH_VERSION finch
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.FINCH_BOT_TOKEN }}
      - name: Silently install
        run: |
          cd $(brew --repo homebrew/cask)
          brew install --cask ./Casks/finch.rb
      - name: Run e2e tests
        run: |
          export PATH="/opt/homebrew/opt/libtool/libexec/gnubin:$PATH"
          INSTALLED=true make test-e2e
      - name: Silently uninstall
        if: ${{ always() }}
        run: |
          cd $(brew --repo homebrew/cask)
          brew uninstall --cask ./Casks/finch.rb
          if [ -d "/Applications/Finch" ]; then
            echo ERROR: Finch is not uninstalled
            exit 1
          fi

  pr-to-homebrew:
    needs: macos-amd64-test-installer
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Open a pull request to homebrwe-cask
        run: brew bump-cask-pr -n --version=${FINCH_VERSION} finch
        env:
          FINCH_VERSION: ${{ needs.get-latest-tag.outputs.version }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.FINCH_BOT_TOKEN }}
        
